# Generated by Django 4.2.9 on 2026-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="source_website",
            field=models.CharField(
                choices=[
                    ("encuentra24", "Encuentra24"),
                    ("crrealestate", "CR Real Estate"),
                    ("coldwellbanker", "Coldwell Banker"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Website where property was found",
                max_length=50,
                verbose_name="Source Website",
            ),
        ),
    ]
