# Generated by Django 4.2.9 on 2026-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_add_source_website_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="date_listed",
            field=models.DateField(
                blank=True,
                help_text="Date property was listed on source website",
                null=True,
                verbose_name="Date Listed",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="internal_property_id",
            field=models.CharField(
                blank=True,
                help_text="Internal property ID from source website",
                max_length=50,
                null=True,
                verbose_name="Internal Property ID",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_id",
            field=models.CharField(
                blank=True,
                help_text="Public listing ID from source website",
                max_length=50,
                null=True,
                verbose_name="Listing ID",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_status",
            field=models.CharField(
                blank=True,
                help_text="Status from source website (Active, Published, Sold, Pending)",
                max_length=50,
                null=True,
                verbose_name="Listing Status",
            ),
        ),
    ]
