databases:
- cluster_name: app-0ce03331-db28-4bbb-b48e-5581a645561a
  db_name: db
  db_user: doadmin
  engine: PG
  name: app-0ce03331-db28-4bbb-b48e-5581
  production: true
  version: "17"
ingress:
  rules:
  - match:
      path:
        prefix: /chat
    component:
      name: web
  - match:
      path:
        prefix: /properties
    component:
      name: web
  - match:
      path:
        prefix: /conversations
    component:
      name: web
  - match:
      path:
        prefix: /documents
    component:
      name: web
  - match:
      path:
        prefix: /ingest
    component:
      name: web
  - match:
      path:
        prefix: /health
    component:
      name: web
  - match:
      path:
        prefix: /admin
    component:
      name: web
  - match:
      path:
        prefix: /static
    component:
      name: web
  - match:
      path:
        prefix: /
    component:
      name: frontend
name: kp-realestate
region: nyc
services:
- dockerfile_path: ./backend/Dockerfile
  source_dir: ./backend
  envs:
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: config.settings.production
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "False"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:W2u4FUXFXfqF9SocgHn+Bu7xb8RYwuqd:8cr71j0Pu2HiapwJK1e5Rc/OAzbHZu3rSJAiTT4=]
  - key: ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: .ondigitalocean.app,localhost,127.0.0.1,100.127.0.0/16
  - key: CORS_ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://${APP_DOMAIN}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${app-0ce03331-db28-4bbb-b48e-5581.DATABASE_URL}
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:gZCzmRzyPeqXcrBsArZHfAM+X/om7MsY:oOQPyqvbxntRutK0uMOZSK/i9iyADsbZBt+4s2pflWtI]
  - key: OPENAI_MODEL_CHAT
    scope: RUN_AND_BUILD_TIME
    value: gpt-4o-mini
  - key: OPENAI_MODEL_COMPLEX
    scope: RUN_AND_BUILD_TIME
    value: gpt-4o
  - key: SECURE_SSL_REDIRECT
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: SECURE_HSTS_SECONDS
    scope: RUN_AND_BUILD_TIME
    value: "31536000"
  - key: SESSION_COOKIE_SECURE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  - key: CSRF_COOKIE_SECURE
    scope: RUN_AND_BUILD_TIME
    value: "True"
  github:
    branch: main
    deploy_on_push: true
    repo: 1di210299/real-estate-llm-generator
  health_check:
    failure_threshold: 3
    http_path: /health/
    initial_delay_seconds: 60
    period_seconds: 30
    success_threshold: 1
    timeout_seconds: 10
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
- build_command: npm ci && npm run build
  envs:
  - key: VITE_API_URL
    scope: BUILD_TIME
    value: ${APP_URL}
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: 1di210299/real-estate-llm-generator
  health_check:
    failure_threshold: 3
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    success_threshold: 1
    timeout_seconds: 5
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: frontend
  run_command: npm start
  source_dir: ./frontend
