# =============================================================================
# DIGITAL OCEAN APP PLATFORM CONFIGURATION
# =============================================================================
name: kp-realestate
region: nyc

# Django Backend API
services:
  - name: web
    github:
      repo: 1di210299/real-estate-llm-generator
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    routes:
      - path: /api
      - path: /admin
      - path: /static
    
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      
      - key: DEBUG
        value: "False"
      
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET
      
      - key: ALLOWED_HOSTS
        value: .ondigitalocean.app,localhost,127.0.0.1,100.127.0.0/16
      
      - key: CORS_ALLOWED_ORIGINS
        value: https://${APP_DOMAIN}
      
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
      
      - key: OPENAI_MODEL_CHAT
        value: gpt-4o-mini
      
      - key: OPENAI_MODEL_COMPLEX
        value: gpt-4o
      
      - key: SECURE_SSL_REDIRECT
        value: "True"
      
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      
      - key: SESSION_COOKIE_SECURE
        value: "True"
      
      - key: CSRF_COOKIE_SECURE
        value: "True"
    
    health_check:
      http_path: /api/health/
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

# React Frontend (Static Site)
static_sites:
  - name: frontend
    github:
      repo: 1di210299/real-estate-llm-generator
      branch: main
      deploy_on_push: true
    
    source_dir: /data-collector-frontend
    environment_slug: node-js
    build_command: npm ci && npm run build
    output_dir: dist
    
    routes:
      - path: /
    
    envs:
      - key: VITE_API_URL
        value: ${web.PUBLIC_URL}

# PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "17"
    production: false
