# =============================================================================
# DIGITAL OCEAN APP PLATFORM CONFIGURATION
# =============================================================================
name: kp-real-estate-llm
region: nyc

# Django Backend API
services:
  - name: web
    github:
      repo: 1di210299/real-estate-llm-generator
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    build_command: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    run_command: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 2 --threads 2 --timeout 120
    
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 8080
    
    routes:
      - path: /api
      - path: /admin
    
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      
      - key: DEBUG
        value: "False"
      
      - key: SECRET_KEY
        value: ${SECRET_KEY}
        type: SECRET
      
      - key: ALLOWED_HOSTS
        value: .ondigitalocean.app,localhost,127.0.0.1,100.127.0.0/16
      
      - key: CORS_ALLOWED_ORIGINS
        value: ${frontend.PUBLIC_URL}
      
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
      
      - key: OPENAI_MODEL_CHAT
        value: gpt-4o-mini
      
      - key: OPENAI_MODEL_COMPLEX
        value: gpt-4o
      
      - key: SECURE_SSL_REDIRECT
        value: "True"
      
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      
      - key: SESSION_COOKIE_SECURE
        value: "True"
      
      - key: CSRF_COOKIE_SECURE
        value: "True"
    
    health_check:
      http_path: /api/health/
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

# React Frontend (Static Site)
static_sites:
  - name: frontend
    github:
      repo: 1di210299/real-estate-llm-generator
      branch: main
      deploy_on_push: true
    
    source_dir: /data-collector-frontend
    build_command: npm install && npm run build
    output_dir: dist
    
    routes:
      - path: /
    
    envs:
      - key: VITE_API_URL
        value: ${web.PUBLIC_URL}

# PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "17"
    production: true
    cluster_name: app-0ce03331-db28-4bbb-b48e-5581a645561a
    db_name: db
    db_user: db
