# Generated by Django 5.0.1 on 2026-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_property_price_details_alter_property_price_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="Type of content: tour, real_estate, restaurant, etc.",
                max_length=50,
                null=True,
                verbose_name="Content Type",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="page_type",
            field=models.CharField(
                blank=True,
                help_text="Type of page: specific, general",
                max_length=50,
                null=True,
                verbose_name="Page Type",
            ),
        ),
    ]
