# Generated by Django 5.0.1 on 2026-01-21 12:31

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("properties", "0011_property_content_type_property_page_type"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalTipsGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="Destination"),
                ),
                (
                    "tip_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Tips General Guide",
                "verbose_name_plural": "Local Tips General Guides",
                "db_table": "local_tips_general",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocalTipsSpecific",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tip_title",
                    models.CharField(max_length=300, verbose_name="Tip Title"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Tip",
                "verbose_name_plural": "Local Tips",
                "db_table": "local_tips_specific",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealEstateGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(
                        help_text="City or region covered",
                        max_length=200,
                        verbose_name="Destination",
                    ),
                ),
                (
                    "total_properties",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Properties"
                    ),
                ),
                (
                    "price_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Min Price (USD)",
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Max Price (USD)",
                    ),
                ),
                (
                    "property_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Property Types Available",
                    ),
                ),
                (
                    "popular_areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Real Estate General Guide",
                "verbose_name_plural": "Real Estate General Guides",
                "db_table": "real_estate_general",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealEstateSpecific",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("condo", "Condominium"),
                            ("villa", "Villa"),
                            ("land", "Land"),
                            ("commercial", "Commercial"),
                            ("apartment", "Apartment"),
                        ],
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("off_market", "Off Market"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Price (USD)",
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(blank=True, null=True, verbose_name="Bedrooms"),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Bathrooms",
                    ),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Square Meters",
                    ),
                ),
                (
                    "lot_size_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Lot Size (m²)",
                    ),
                ),
                (
                    "amenities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "year_built",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Year Built"
                    ),
                ),
                (
                    "parking_spaces",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Parking Spaces"
                    ),
                ),
                (
                    "hoa_fee_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="HOA Fee (Monthly)",
                    ),
                ),
                (
                    "property_tax_annual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Property Tax (Annual)",
                    ),
                ),
                (
                    "listing_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Listing ID"
                    ),
                ),
                (
                    "date_listed",
                    models.DateField(blank=True, null=True, verbose_name="Date Listed"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Real Estate Property",
                "verbose_name_plural": "Real Estate Properties",
                "db_table": "real_estate_specific",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="Destination"),
                ),
                (
                    "total_restaurants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Restaurants"
                    ),
                ),
                (
                    "cuisine_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "price_ranges",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "neighborhoods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant General Guide",
                "verbose_name_plural": "Restaurant General Guides",
                "db_table": "restaurant_general",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSpecific",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant_name",
                    models.CharField(max_length=200, verbose_name="Restaurant Name"),
                ),
                (
                    "cuisine_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True,
                        help_text="$, $$, $$$, $$$$",
                        max_length=20,
                        null=True,
                        verbose_name="Price Range",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "number_of_reviews",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Reviews"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Website"
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Opening Hours"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
                "db_table": "restaurant_specific",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="Destination"),
                ),
                (
                    "total_tours",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Tours"
                    ),
                ),
                (
                    "activity_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "price_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Min Price (USD)",
                    ),
                ),
                (
                    "price_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Max Price (USD)",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour General Guide",
                "verbose_name_plural": "Tour General Guides",
                "db_table": "tour_general",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourSpecific",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tour_name",
                    models.CharField(max_length=300, verbose_name="Tour Name"),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Difficulty"
                    ),
                ),
                (
                    "price_adult",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price Adult (USD)",
                    ),
                ),
                (
                    "price_child",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Price Child (USD)",
                    ),
                ),
                (
                    "price_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Price Details"
                    ),
                ),
                (
                    "group_size_max",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Max Group Size"
                    ),
                ),
                (
                    "activity_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "included_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "excluded_items",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "meeting_point",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Meeting Point",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
                "db_table": "tour_specific",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportationGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("region", models.CharField(max_length=200, verbose_name="Region")),
                (
                    "transport_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "total_routes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Routes"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation General Guide",
                "verbose_name_plural": "Transportation General Guides",
                "db_table": "transportation_general",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportationSpecific",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name", max_length=300, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City, region, or area",
                        max_length=200,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(
                        choices=[
                            ("encuentra24", "Encuentra24"),
                            ("crrealestate", "CR Real Estate"),
                            ("coldwellbanker", "Coldwell Banker"),
                            ("tripadvisor", "TripAdvisor"),
                            ("desafio", "Desafio"),
                            ("rome2rio", "Rome2Rio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Source Website",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500, unique=True, verbose_name="Source URL"
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="Raw HTML"),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Extraction Confidence",
                    ),
                ),
                (
                    "field_confidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-field confidence scores and content-specific extra fields",
                        verbose_name="Field Confidence & Extra Data",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Extracted At"
                    ),
                ),
                (
                    "user_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Visible to Roles",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1536,
                        null=True,
                        verbose_name="Embedding Vector",
                    ),
                ),
                (
                    "content_for_search",
                    models.TextField(
                        blank=True,
                        help_text="Pre-computed text content for embeddings",
                        null=True,
                        verbose_name="Content for Search",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route_name",
                    models.CharField(max_length=300, verbose_name="Route Name"),
                ),
                (
                    "departure_location",
                    models.CharField(max_length=200, verbose_name="Departure Location"),
                ),
                (
                    "arrival_location",
                    models.CharField(max_length=200, verbose_name="Arrival Location"),
                ),
                (
                    "transport_type",
                    models.CharField(
                        help_text="Bus, shuttle, taxi, car, plane, etc.",
                        max_length=50,
                        verbose_name="Transport Type",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance (km)",
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Min Price (USD)",
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Max Price (USD)",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="How often service runs",
                        max_length=200,
                        null=True,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Operator"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_items",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation Route",
                "verbose_name_plural": "Transportation Routes",
                "db_table": "transportation_specific",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "image_url",
                    models.URLField(max_length=500, verbose_name="Image URL"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Caption"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Order")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "content_images",
                "ordering": ["order", "-is_primary", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="content_ima_content_c52cad_idx",
                    )
                ],
            },
        ),
    ]
